name: ht_countries_repository
description: A Flutter package providing a repository implementation for managing news countries.
repository: https://github.com/headlines-toolkit/ht-countries-repository
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  ht_countries_client:
    git:
      url: https://github.com/headlines-toolkit/ht-countries-client.git
  ht_shared:
    git:
      url: https://github.com/headlines-toolkit/ht-shared.git
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
